### PR TITLE
Update - add servicemonitor

### PR DESCRIPTION
**Pull request by Ronan-WeScale**
All options aren't tested.  
Tested with servicemonitor.enabled : true   
work's as espected

### CODE REVIEW

**Comment by Ronan-WeScale** [comment]
fix #41

**Comment by blind-oracle** [comment]
Probably we need helm chart version bump, or not?

**Comment by Ronan-WeScale** [comment]
of course, you can do it after merge or you want I do it ?

**Comment by blind-oracle** [comment]
Yes, please update appropriate files in the repo and the chart will be scanned by the ArtifactHub automatically

**Comment by Ronan-WeScale** [comment]
all is good ?

**Comment by Ronan-WeScale** [comment]
bump

**Comment by Ronan-WeScale** [comment]
replaced by #46

**Pull request closed without merging**
