### PR TITLE
feat(chart): add a helm chart

### LINKED ISSUE #32: Suggestion: Create a helm chart
Good afternoon !
I find your project very useful and wanted to implement it since I currently have the use case with mimir. However, I noticed that there are only the manifest files for the k8s resources and I couldn't help but think that an helm chart would allow more people to easily set up and customize your solution ! 
It is posible to [publish one and claim ownership on Artifact Hub](https://artifacthub.io/docs/topics/repositories/helm-charts/) 
If you are interested, I could create a merge request with a basic helm chart with templated manifests, let me know !

### PR DESCRIPTION
**Pull request by WhiteDiamondz**
Note: 

This does not publish the chart to sites like https://artifacthub.io/packages/helm. If wanted, a few steps are required by the author of the app (see https://artifacthub.io/docs/topics/repositories/helm-charts/, https://leeyoongti.medium.com/helm-in-kubernetes-part-4-publish-helm-chart-to-artifact-hub-using-github-pages-ab7f55904faa).

Closes #32

### CODE REVIEW

**Comment by blind-oracle** [comment]
Thanks, i'll try to push that to repos

**Comment by blind-oracle** [comment]
I guess it also needs some kind of `index.yaml` to be processed by the repo? Can you add that too?

**Comment by WhiteDiamondz** [comment]
> I guess it also needs some kind of `index.yaml` to be processed by the repo? Can you add that too?

Sure, do you want me to create a new pull request for this purpose ?

**Comment by blind-oracle** [comment]
Yes, since this one is already merged :) If all file structure would be ready - I'll add it to the relevant repos etc.

**Comment by WhiteDiamondz** [comment]
@blind-oracle Looks like it needs to be pushed to a specific branch: `gh-pages`. Any chance you could create the branch with this name so I can select it as the pull request's target ?

**Comment by adberger** [comment]
@blind-oracle Any chance of making the helm chart available via `gh-pages`?

**Comment by blind-oracle** [comment]
Sorry, was bit busy.

According to https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site you don't really need `gh-pages`, it can work from any branch and subfolder i.e. `master`. So I guess we can just put the relevant `index.yaml` into some folder e.g. `deploy/k8s` and I'll configure to publish it.

**Comment by adberger** [comment]
> Sorry, was bit busy.
> 
> According to https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site you don't really need `gh-pages`, it can work from any branch and subfolder i.e. `master`. So I guess we can just put the relevant `index.yaml` into some folder e.g. `deploy/k8s` and I'll configure to publish it.

That would be awesome!

**Comment by blind-oracle** [comment]
Just create an MR with index.yaml and i'll do it.

**Comment by adberger** [comment]
It seems to me, that the branch is needed. There is an official tutorial from helm itself: https://helm.sh/docs/howto/chart_releaser_action/

**Pull request merged**
